.Dd $Mdocdate: July 13 2022 $
.Dt LUA_GETHOOK 3
.Os
.Sh NAME
.Nm lua_gethook
.Nd returns the current hook function, function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft lua_Hook
.Fn lua_gethook "lua_State *L"
.Sh DESCRIPTION
.Fn lua_gethook
returns the current hook function.
.Sh RETURN VALUES
Returns the current hook function.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_gethook
manual page was written by Sergey Bronnikov.
