.Dd $Mdocdate: July 14 2022 $
.Dt LUA_GETTOP 3
.Os
.Sh NAME
.Nm lua_gettop
.Nd returns the index of the top element in the stack, function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_gettop "lua_State *L"
.Sh DESCRIPTION
.Fn lua_gettop
returns the index of the top element in the stack.
Because indices start at 1, this result is equal to the number of elements in
the stack (and so 0 means an empty stack).
.Sh RETURN VALUES
Returns the index of the top element in the stack.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_gettop
manual page was written by Sergey Bronnikov.
