.Dd $Mdocdate: July 15 2022 $
.Dt LUA_SETFENV 3
.Os
.Sh NAME
.Nm lua_setfenv
.Nd pops a table from the stack and sets it as the new environment for the
value, function indicator
.Bq -1, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_setfenv "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_setfenv
pops a table from the stack and sets it as the new environment for the value at
the given index.
.Sh RETURN VALUES
If the value at the given index is neither a function nor a thread nor a
userdata,
.Fn lua_setfenv
returns 0.
Otherwise it returns 1.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_setfenv
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
