.Dd $Mdocdate: July 15 2022 $
.Dt LUA_NUMBER 3
.Os
.Sh NAME
.Nm lua_Number
.Nd type of numbers in Lua
.Sh SYNOPSIS
.In lua.h
.Vt typedef double lua_Number ;
.Sh DESCRIPTION
The type of numbers in Lua.
By default, it is double, but that can be changed in
.In luaconf.h .
.Pp
Through the configuration file you can change Lua to operate with another type
for numbers (e.g., float or long).
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Vt lua_Number
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
