.Dd $Mdocdate: July 14 2022 $
.Dt LUA_GETMETATABLE 3
.Os
.Sh NAME
.Nm lua_getmetatable
.Nd pushes onto the stack the metatable of the value at the given acceptable index, function indicator
.Bo -0, + Pq 0|1 ,
-
.Bc
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_getmetatable "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_getmetatable
pushes onto the stack the metatable of the value at the given acceptable index.
.Sh RETURN VALUES
If the
.Fa index
is not valid, or if the value does not have a metatable, the function returns 0
and pushes nothing on the stack.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_getmetatable
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
