.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_LOADSTRING 3
.Os
.Sh NAME
.Nm luaL_loadstring
.Nd loads a string as a Lua chunk, function indicator
.Bq -0, +1, m
.Sh SYNOPSIS
.In lauxlib.h
.Ft int
.Fn luaL_loadstring "lua_State *L" "const char *s"
.Sh DESCRIPTION
.Fn luaL_loadstring
loads a string as a Lua chunk.
This function uses
.Xr lua_load 3
to load the chunk in the zero-terminated string
.Fa s .
.Pp
This function returns the same results as
.Xr lua_load 3 .
.Pp
Also as
.Xr lua_load 3 ,
this function only loads the chunk; it does not run it.
.Sh SEE ALSO
.Xr lua_load 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_loadstring
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
