.Dd $Mdocdate: July 22 2022 $
.Dt LUAL_ADDSTRING 3
.Os
.Sh NAME
.Nm luaL_addstring
.Nd adds the zero-terminated string to the buffer, function indicator
.Bq -0, +0, m
.Sh SYNOPSIS
.In lauxlib.h
.Ft void
.Fn luaL_addstring "luaL_Buffer *B" "const char *s"
.Sh DESCRIPTION
.Fn luaL_addstring
adds the zero-terminated string pointed to by
.Fa s
to the buffer
.Fa B
.Pq see Xr luaL_Buffer 3 .
The string may not contain embedded zeros.
.Sh SEE ALSO
.Xr luaL_Buffer 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_addstring
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
