.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_DOFILE 3
.Os
.Sh NAME
.Nm luaL_dofile
.Nd loads and runs the given file
.Sh SYNOPSIS
.In lauxlib.h
.Ft int
.Fn luaL_dofile "lua_State *L" "const char *filename"
.Sh DESCRIPTION
.Fn luaL_dofile
loads and runs the given file.
It is defined as the following macro:
.Pp
.Bd -literal -offset indent -compact
(luaL_loadfile(L, filename) || lua_pcall(L, 0, LUA_MULTRET, 0))
.Ed
.Sh RETURN VALUES
It returns 0 if there are no errors or 1 in case of errors.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_dofile
manual page was written by Sergey Bronnikov.
