.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_ERROR 3
.Os
.Sh NAME
.Nm luaL_error
.Nd raises an error, function indicator
.Bq -0, +0, v
.Sh SYNOPSIS
.In lauxlib.h
.Ft int
.Fn luaL_error "lua_State *L" "const char *fmt" "..."
.Sh DESCRIPTION
.Fn luaL_error
raises an error.
The error message format is given by
.Fa fmt
plus any extra arguments, following the same rules of
.Xr lua_pushfstring 3 .
It also adds at the beginning of the message the file name and the line number
where the error occurred, if this information is available.
.Pp
This function never returns, but it is an idiom to use it in C functions as
return
.Em luaL_error(args) .
.Sh SEE ALSO
.Xr lua_pushfstring 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_error
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
