.Dd $Mdocdate: July 26 2022 $
.Dt LUAL_OPTNUMBER 3
.Os
.Sh NAME
.Nm luaL_optnumber
.Nd if the function argument is a number, returns this number, function indicator
.Bq -0, +0, v
.Sh SYNOPSIS
.In lauxlib.h
.Ft lua_Number
.Fn luaL_optnumber "lua_State *L" "int narg" "lua_Number d"
.Sh DESCRIPTION
.Fn luaL_optnumber
if the function argument
.Fa narg
is a number, returns this number.
If this argument is absent or is
.Dv nil ,
returns
.Fa d .
Otherwise, raises an error.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_optnumber
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
