.Dd $Mdocdate: July 18 2022 $
.Dt LUA_POP 3
.Os
.Sh NAME
.Nm lua_pop
.Nd pops n elements from the stack, function indicator
.Bq -n, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft void
.Fn lua_pop "lua_State *L" "int n"
.Sh DESCRIPTION
.Fn lua_pop
pops
.Fa n
elements from the stack.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_pop
manual page was written by Sergey Bronnikov.
