.Dd $Mdocdate: July 15 2022 $
.Dt LUA_RAWSETI 3
.Os
.Sh NAME
.Nm lua_rawseti
.Nd pops the value from the stack
.Sh SYNOPSIS
.In lua.h
.Ft void
.Fn lua_rawseti "lua_State *L" "int index" "int n"
.Sh DESCRIPTION
.Fn lua_rawseti
does the equivalent of t[n] = v, where t is the value at the given valid index
and v is the value at the top of the stack.
.Pp
This function pops the value from the stack.
The assignment is raw; that is, it does not invoke metamethods.
.Sh HISTORY
The
.Fn lua_rawseti
manual page was written by Sergey Bronnikov.
