.Dd $Mdocdate: July 14 2022 $
.Dt LUA_CLOSE 3
.Os
.Sh NAME
.Nm lua_close
.Nd destroys all objects and frees all dynamic memory, function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft void
.Fn lua_close "lua_State *L"
.Sh DESCRIPTION
.Fn lua_close
destroys all objects in the given Lua state (calling the corresponding
garbage-collection metamethods, if any) and frees all dynamic memory used by
this state.
On several platforms, you may not need to call this function, because all
resources are naturally released when the host program ends.
On the other hand, long-running programs, such as a daemon or a web server,
might need to release states as soon as they are not needed, to avoid growing
too large.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_close
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
