.Dd $Mdocdate: July 15 2022 $
.Dt LUA_ISTHREAD 3
.Os
.Sh NAME
.Nm lua_isthread
.Nd check whether a value is a thread, function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_isthread "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_isthread
returns 1 if the value at the given acceptable index is a thread, and 0
otherwise.
.Sh RETURN VALUES
Returns 1 if the value at the given acceptable index is a thread, and 0
otherwise.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_isthread
manual page was written by Sergey Bronnikov.
