.Dd $Mdocdate: July 18 2022 $
.Dt LUA_WRITER 3
.Os
.Sh NAME
.Nm lua_Writer
.Nd type of the writer function used by
.Xr lua_dump 3
.Sh SYNOPSIS
.In lua.h
.Ft typedef int *
.Fn lua_Writer "lua_State *L" "const void* p" "size_t sz" "void* ud"
.Sh DESCRIPTION
.Vt lua_Writer
type of the writer function used by
.Xr lua_dump 3 .
Every time it produces another piece of chunk,
.Xr lua_dump 3
calls the writer, passing along the buffer to be written
.Pq Fa p ,
its size
.Pq Fa sz ,
and the data parameter supplied to
.Xr lua_dump 3 .
.Sh RETURN VALUES
The writer returns an error code: 0 means no errors; any other value means an
error and stops
.Xr lua_dump 3
from calling the writer again.
.Sh HISTORY
The
.Vt lua_Writer
manual page was written by Sergey Bronnikov.
