.Dd $Mdocdate: July 18 2022 $
.Dt LUA_PUSHVFSTRING 3
.Os
.Sh NAME
.Nm lua_pushvfstring
.Nd pushes onto the stack a formatted string and returns a pointer to this string, function indicator
.Bq -0, +1, m
.Sh SYNOPSIS
.In lua.h
.Ft const char *
.Fn lua_pushvfstring "lua_State *L" "const char *fmt" "va_list argp"
.Sh DESCRIPTION
.Fn lua_pushvfstring
pushes onto the stack a formatted string and returns a pointer to this string.
Equivalent to
.Xr lua_pushfstring 3 ,
except that it receives a
.Fa va_list
instead of a variable number of arguments.
.Sh SEE ALSO
.Xr lua_pushfstring 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_pushvfstring
manual page was written by Sergey Bronnikov.
