.Dd $Mdocdate: July 14 2022 $
.Dt LUA_ISNONE 3
.Os
.Sh NAME
.Nm lua_isnone
.Nd check whether a value is not valid
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_isnone "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_isnone
returns 1 if the given acceptable index is not valid, and 0 otherwise.
.Sh RETURN VALUES
Returns 1 if the given acceptable index is not valid (that is, it refers to an
element outside the current stack), and 0 otherwise.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_isnone
manual page was written by Sergey Bronnikov.
