.Dd $Mdocdate: July 15 2022 $
.Dt LUA_ISUSERDATA 3
.Os
.Sh NAME
.Nm lua_isuserdata
.Nd check whether a value is a userdata, function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_isuserdata "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_isuserdata
returns 1 if the value at the given acceptable index is a userdata (either full
or light), and 0 otherwise.
.Sh RETURN VALUES
Returns 1 if the value at the given acceptable index is a userdata (either full
or light), and 0 otherwise.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_isuserdata
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
