.Dd $Mdocdate: July 14 2022 $
.Dt LUA_TOCFUNCTION 3
.Os
.Sh NAME
.Nm lua_tocfunction
.Nd converts a value to a C function
.Sh SYNOPSIS
.In lua.h
.Ft lua_CFunction
.Fn lua_tocfunction "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_tocfunction
converts a value at the given acceptable index to a C function.
.Sh RETURN VALUES
That value must be a C function; otherwise, returns
.Dv NULL .
.Sh HISTORY
The
.Fn lua_tocfunction
manual page was written by Sergey Bronnikov.
