.Dd $Mdocdate: July 15 2022 $
.Dt LUA_REPLACE 3
.Os
.Sh NAME
.Nm lua_replace
.Nd moves the top element into the given position
.Sh SYNOPSIS
.In lua.h
.Ft void
.Fn lua_replace "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_replace
moves the top element into the given position (and pops it), without shifting
any element (therefore replacing the value at the given position).
.Sh HISTORY
The
.Fn lua_replace
manual page was written by Sergey Bronnikov.
