.Dd $Mdocdate: July 14 2022 $
.Dt LUA_STATUS 3
.Os
.Sh NAME
.Nm lua_status
.Nd returns the status of the thread L, function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_status "lua_State *L"
.Sh DESCRIPTION
.Fn lua_status
returns the status of the thread L.
.Sh RETURN VALUES
The status can be 0 for a normal thread, an error code if the thread finished
its execution with an error, or
.Dv LUA_YIELD
if the thread is suspended.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_status
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
