.Dd $Mdocdate: July 15 2022 $
.Dt LUA_SETTABLE 3
.Os
.Sh NAME
.Nm lua_settable
.Nd pops both the key and the value from the stack, function indicator
.Bq -2, +0, e
.Sh SYNOPSIS
.In lua.h
.Ft void
.Fn lua_settable "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_settable
does the equivalent to t[k] = v, where t is the value at the given valid index,
v is the value at the top of the stack, and k is the value just below the top.
.Pp
This function pops both the key and the value from the stack.
As in Lua, this function may trigger a metamethod for the
.Qq newindex
event.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_settable
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
