.Dd $Mdocdate: July 13 2022 $
.Dt LUA_TOTHREAD 3
.Os
.Sh NAME
.Nm lua_tothread
.Nd converts the value to a Lua thread
.Sh SYNOPSIS
.In lua.h
.Ft lua_State *
.Fn lua_tothread "lua_State *L" "int index"
.Sh DESCRIPTION
.Fn lua_tothread
converts the value at the given acceptable index to a Lua thread (represented
as lua_State *).
This value must be a thread; otherwise, the function returns
.Dv NULL .
.Sh RETURN VALUES
Returns Lua thread represented as lua_State* and returns
.Dv NULL
when value is not a thread.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_gethook
manual page was written by Sergey Bronnikov.
