.Dd $Mdocdate: July 18 2022 $
.Dt LUA_PUSHTHREAD 3
.Os
.Sh NAME
.Nm lua_pushthread
.Nd pushes the thread onto the stack, function indicator
.Bq -0, +1, -
.Sh SYNOPSIS
.In lua.h
.Ft int
.Fn lua_pushthread "lua_State *L"
.Sh DESCRIPTION
.Fn lua_pushthread
pushes the thread represented by
.Fa L
onto the stack.
Returns 1 if this thread is the main thread of its state.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn lua_pushthread
manual page was written by Sergey Bronnikov.
