.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_GETMETATABLE 3
.Os
.Sh NAME
.Nm luaL_getmetatable
.Nd pushes onto the stack the metatable associated with name in the registry,
function indicator
.Bq -0, +1, -
.Sh SYNOPSIS
.In lauxlib.h
.Ft void
.Fn luaL_getmetatable "lua_State *L" "const char *tname"
.Sh DESCRIPTION
.Fn luaL_getmetatable
pushes onto the stack the metatable associated with name
.Fa tname
in the registry
.Pq see Xr luaL_newmetatable 3 .
.Sh SEE ALSO
.Xr luaL_newmetatable 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_getmetatable
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
