.Dd $Mdocdate: July 26 2022 $
.Dt LUAL_OPTINT 3
.Os
.Sh NAME
.Nm luaL_optint
.Nd casts a number to an int, function indicator
.Bq -0, +0, v
.Sh SYNOPSIS
.In lauxlib.h
.Ft int
.Fn luaL_optint "lua_State *L" "int narg" "int d"
.Sh DESCRIPTION
.Fn luaL_optint
if the function argument
.Fa narg
is a number, returns this number cast to an int.
If this argument is absent or is
.Dv nil ,
returns
.Fa d .
Otherwise, raises an error.
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_optint
manual page was written by Sergey Bronnikov.
