.Dd $Mdocdate: July 22 2022 $
.Dt LUAL_ADDSIZE 3
.Os
.Sh NAME
.Nm luaL_addsize
.Nd adds to the buffer a string, function indicator
.Bq -0, +0, m
.Sh SYNOPSIS
.In lauxlib.h
.Ft void
.Fn luaL_addsize "luaL_Buffer *B" "size_t n"
.Sh DESCRIPTION
.Fn luaL_addsize
adds to the buffer
.Fa B
.Pq see Xr luaL_Buffer 3
a string of length
.Fa n
previously copied to the buffer area
.Pq see Xr luaL_prepbuffer 3 .
.Sh SEE ALSO
.Xr luaL_Buffer 3 ,
.Xr luaL_prepbuffer 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_addsize
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
