.Dd $Mdocdate: July 22 2022 $
.Dt LUAL_ADDSIZE 3
.Os
.Sh NAME
.Nm luaL_addsize
.Nd adds to the buffer a string
.Sh SYNOPSIS
.In lauxlib.h
.Ft void
.Fn luaL_addsize "luaL_Buffer *B" "size_t n"
.Sh DESCRIPTION
.Fn luaL_addsize
adds to the buffer
.Fa B
.Pq see Xr luaL_Buffer 3
a string of length
.Fa n
previously copied to the buffer area
.Pq see Xr luaL_prepbuffer 3 .
.Sh HISTORY
The
.Fn luaL_addsize
manual page was written by Sergey Bronnikov.
