.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_CHECKNUMBER 3
.Os
.Sh NAME
.Nm luaL_checknumber
.Nd checks whether the function argument narg is a number and returns this
number
.Sh SYNOPSIS
.In lauxlib.h
.Ft lua_Number
.Fn luaL_checknumber "lua_State *L" "int narg"
.Sh DESCRIPTION
.Fn luaL_checknumber
checks whether the function argument
.Fa narg
is a number and returns this number.
.Sh HISTORY
The
.Fn luaL_checknumber
manual page was written by Sergey Bronnikov.
