.Dd $Mdocdate: July 26 2022 $
.Dt LUAL_PREPBUFFER 3
.Os
.Sh NAME
.Nm luaL_prepbuffer
.Nd prepares a buffer
.Xr luaL_Buffer 3 ,
function indicator
.Bq -0, +0, -
.Sh SYNOPSIS
.In lauxlib.h
.Ft char *
.Fn luaL_prepbuffer "luaL_Buffer *B"
.Sh DESCRIPTION
.Fn luaL_prepbuffer
returns an address to a space of size
.Dv LUAL_BUFFERSIZE
where you can copy a
string to be added to buffer
.Fa B
.Pq see Xr luaL_Buffer 3 .
After copying the string into this space you must call
.Xr luaL_addsize 3
with the size of the string to actually add it to the buffer.
.Sh SEE ALSO
.Xr luaL_addsize 3 ,
.Xr luaL_Buffer 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_prepbuffer
manual page was written by Sergey Bronnikov.
