.Dd $Mdocdate: July 26 2022 $
.Dt LUAL_CALLMETA 3
.Os
.Sh NAME
.Nm luaL_callmeta
.Nd calls a metamethod, function indicator
.Bo -0, + Pq 0|1 ,
e
.Bc
.Sh SYNOPSIS
.In lauxlib.h
.Ft int
.Fn luaL_callmeta "lua_State *L" "int obj" "const char *e"
.Sh DESCRIPTION
.Fn luaL_callmeta
calls a metamethod.
.Sh RETURN VALUES
If the object at index obj has a metatable and this metatable has a field
.Fa e ,
this function calls this field and passes the object as its only argument.
In this case this function returns 1 and pushes onto the stack the value
returned by the call.
If there is no metatable or no metamethod, this function returns 0 (without
pushing any value on the stack).
.Sh SEE ALSO
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_callmeta
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
