.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_CHECKSTRING 3
.Os
.Sh NAME
.Nm luaL_checkstring
.Nd checks whether the function argument is a string and returns this string, function indicator
.Bq -0, +0, v
.Sh SYNOPSIS
.In lauxlib.h
.Ft const char *
.Fn luaL_checkstring "lua_State *L" "int narg"
.Sh DESCRIPTION
.Fn luaL_checkstring
checks whether the function argument
.Fa narg
is a string and returns this string.
.Pp
This function uses
.Xr lua_tolstring 3
to get its result, so all conversions and caveats of that function apply here.
.Sh SEE ALSO
.Xr lua_tolstring 3
.Rs
.%A Roberto Ierusalimschy
.%A Luiz Henrique de Figueiredo
.%A Waldemar Celes
.%T Lua 5.1 Reference Manual
.Re
.Sh HISTORY
The
.Fn luaL_checkstring
manual page is based on Lua Reference Manual 5.1 and was created by Sergey Bronnikov.
