.Dd $Mdocdate: July 24 2022 $
.Dt LUAL_CHECKINT 3
.Os
.Sh NAME
.Nm luaL_checkint
.Nd checks whether the function argument is a number
.Sh SYNOPSIS
.In lauxlib.h
.Ft int
.Fn luaL_checkint "lua_State *L" "int narg"
.Sh DESCRIPTION
.Fn luaL_checkint
checks whether the function argument
.Fa narg
is a number and returns this number cast to an
.Em int         .
.Sh HISTORY
The
.Fn luaL_checkint
manual page was written by Sergey Bronnikov.
