name: Static analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup mandoc
        run: sudo apt install -y mandoc

      - run: sudo make install

      - run: sudo makewhatis

      - run: make check
